import mlab
from models.savepicture import Savepicture

mlab.connect()

# Savepicture(picname='Con đường mùa đông', piclink='https://via.placeholder.com/50x50', picstatus='finished', piclikes=111, picartist='tambui').save()
# Savepicture(picname='Mùa hè tuyết rơi',piclink='https://via.placeholder.com/50x50', picstatus='finished', piclikes=1, picartist='thanhcong').save()
# Savepicture(picname='Hành trang đến trường',piclink='https://via.placeholder.com/50x50', picstatus='finished', piclikes=11111, picartist='quanghuy').save()
# Savepicture(picname='Nơi tình yêu bắt đầu',piclink='https://via.placeholder.com/50x50', picstatus='finished', piclikes=11, picartist='anhminh').save()
# Savepicture(picname='Con chó',piclink='https://via.placeholder.com/50x50', picstatus='finished', piclikes=1111, picartist='hoangcuong').save()
# Savepicture(picname='Dòng sông băng',piclink='https://via.placeholder.com/50x50', picstatus='finished', piclikes=1111111, picartist='anhquan').save()
# Savepicture(picname='Kiếp rong buồn',piclink='https://via.placeholder.com/50x50', picstatus='finished', piclikes=22, picartist='tambui').save()
# Savepicture(picname='Lạc trôi',piclink='https://via.placeholder.com/50x50', picstatus='finished', piclikes=2222, picartist='thanhcong').save()
# Savepicture(picname='Người hãy quên em đi',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='quanghuy').save()
# Savepicture(picname='Mưa đêm tỉnh lẻ',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='anhminh').save()
# Savepicture(picname='Phố không mùa',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='hoangcuong').save()
# Savepicture(picname='Rừng lá thấp',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='anhquan').save()
# Savepicture(picname='Chuyến tàu hoàng hôn',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='tambui').save()
# Savepicture(picname='Xin anh đừng',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='thanhcong').save()
# Savepicture(picname='Thu cuối',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='quanghuy').save()
# Savepicture(picname='Một hai ba bốn năm',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='anhminh').save()

Savepicture(picname='helo mùa đông', piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='hoangcuong').save()
Savepicture(picname='daha tuyết rơi',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='anhquan').save()
Savepicture(picname='chomua đến trường',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='quanghuy').save()
Savepicture(picname='him hi bắt đầu',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='thanhcong').save()
Savepicture(picname='gufh chó',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='anhminh').save()
Savepicture(picname='hfwi băng',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='anhminh').save()
Savepicture(picname='hfakf rong buồn',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='tambui').save()
Savepicture(picname='fhkaf trôi',piclink='https://via.placeholder.com/50x50', picstatus='working', piclikes=0, picartist='quanghuy').save()